### ISSUE TITLE
Links not working 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#43]
List of link problems: 
**introduction**
menu: adaptation_framework -- not appearing 

**toolbox**
1st link on new toolbox menu was greyed out and not working. I fixed the links in the google doc to remove "plan" and reuploaded. I noticed elsewhere in the text adding plan does work on the website, so I added it back to one of the links. Still doesn't work. All the links are now broken again. I opened one of the links in a new tab it reads: http://localhost:8080/adapt/toolbox#adaptation_strategies

**analyze**

**design**
The first link "adaptation strategies" opens the toolbox on the website, but does not go to the # 
in Menu: stakeholder-specific strategies does not go to #
none of the map layers seem to be working in this section 

**monitor** 

menu: climate_justice_academy # does not appear, although it's on the spreadsheet 
**implement** 
Menu: financial_evaluation -- not appearing in menu 
Menu: adapt_oakland_area_evaluation -- not appearing in menu

**Comment by johnvf** [comment]
I just uploaded the latest content locally and took a look - 

/introduction 
**link to 'adaptive management': I was unable to reproduce this (it works as expected on my machine). We may have to look at your machine for this one - you may be on the wrong branch?**

/1_analyze
**link to "about page" doesn't navigate: There is a bad URL for this link - the link points to 'adapt/oakland/about' when it should point to '/adapt/about'. Can you make this fix in the .docx?**

'500' Setback' not scrolling to the heading 'regulatory_efforts': There appears to be an issue with the .docx converter setting IDs for this title because of it's different styling. Typically, as an example, "Oakland ECAP" -> "oakland_ecap". In this case, "Regulatory Efforts" -> "efforts_strong_". 

'Urban Heat Island Effect' does not go to the heading listed: For some reason, although the heading should be '',the .docx exporter has shortened it to 'respiratory_health'.

The 2 items above are now both resolved on Master - the code can now handle headings with a variety of styles.

Open external links in a new window: This now happens in the latest code on 'master'.

**Comment by johnvf** [comment]
Edit: For '500' Setback' not scrolling to the heading 'regulatory_efforts': 👍 

It is possible that I can add a little code to handle these alternate styles. Stay tuned

**Comment by johnvf** [comment]
'500' Setback' not scrolling to the heading 'regulatory_efforts' & 'Urban Heat Island Effect' does not go to the heading listed: Now both resolved on Master - the code can now handle headings with a variety of styles.

**Comment by BioBricoleur** [comment]
Text links within a section are still not working for some reason. The capitalization has been corrected (Try links in implement text section, as an example) but its not converting from tilde to number (#). It is working from menu TOC.

**Comment by johnvf** [comment]
Can you be specific about which links in which section?

**Comment by BioBricoleur** [comment]
Implement Section:

All links within the section.
Links to other sections work, if they don't have #

heres some examples:

We have also developed **project delivery, financing, policy and real estate strategies** that have been shortlisted for Oakland specific implementation. Finally, more general and broadly applicable analysis of some of the topics, including green infrastructure financing mechanisms and alternative stormwater compliance, can be found in the adapt toolbox. 

or

You can use these links to go straight to Stakeholder Specific Strategy sections: **Port, Caltrans, OAB, WOSP.**

**Comment by johnvf** [comment]
Apparently, your keyboard creates a different tilde character - 
U+223D  ∽ e2 88 bd
see also:
http://www.utf8-chartable.de/unicode-utf8-table.pl?start=8704&number=128&names=-

I didn't realize there were so many different tilde characters - probably would have picked a different character for our little workaround next time. Now search/replacing the following:

˜ , ∼ , ∽ , ~

**Comment by BioBricoleur** [comment]
That's crazy! Thank you I think that's a reverse tilde maybe that I was
doing?

So just to confirm it's supposed to be this one...
U+223D ∽ e2 88 bd

And I'll replace all others.

I guess you gotta dip down before you dip up in this tilde world.

Gracias.
On Apr 25, 2016 6:36 PM, "John Victor-Faichney" notifications@github.com
wrote:

Apparently, your keyboard creates a different tilde character -
U+223D ∽ e2 88 bd
see also:
http://www.utf8-chartable.de/unicode-utf8-table.pl?start=8704&number=128&names=-

I didn't realize there were so many different tilde characters - probably
would have picked a different character for our little workaround next
time. Now search/replacing the following:

˜ , ∼ , ∽ , ~
